GET http://localhost:3000
###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
	"email" : "mesra@gmail.com",
	"password" : "myPasswordCom"
}

###
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "email": "dinda@gmail.com",
  "password": "myCustomPassword",
  "fullName": "Dinda Adinda Putri"
}