GET http://localhost:3000/api/v1/funds
###
GET http://localhost:3000/api/v1/fund/1

###
POST http://localhost:3000/api/v1/fund 
Content-Type: application/json

{
  "title": "TSUNAMI ACEHHHH",
  "thumbnail": "praytoAceh.png",
  "goal": 9999990,
  "description": "Lorem Ipsum is simply dummy text of the printing  "
}
###
PATCH http://localhost:3000/api/v1/fund/
Content-Type: application/json

{
  "title": " update euy "
}
###
DELETE http://localhost:3000/api/v1/fund/
